#define DHT_REGISTER_BEGIN 1
#define DHT_REGISTER_ACK 2
#define DHT_REGISTER_FAKE_ACK 3
#define DHT_REGISTER_DONE 4

#define DHT_DEREGISTER_BEGIN 11
#define DHT_DEREGISTER_ACK 12
#define DHT_DEREGISTER_DONE 13
#define DHT_DEREGISTER_DENY 14	

#define DHT_GET_DATA 21	
#define DHT_PUT_DATA 22
#define DHT_DUMP_DATA 23
#define DHT_PUT_DATA_ACK 24
#define DHT_DUMP_DATA_ACK 25
#define DHT_SEND_DATA 26
#define DHT_TRANSFER_DATA 27
#define DHT_NO_DATA 28
	
#define DHT_ACQUIRE_REQUEST 31
#define DHT_ACQUIRE_ACK 32
#define DHT_RELEASE_REQUEST 33
#define DHT_RELEASE_ACK 34
